sudo: required
services:
  - docker
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - gem install bundler
before_script:
  - cp config/database.yml{.sample,}
  - bundle exec rake db:create db:test:prepare
after_success:
  - ./scripts/build
addons:
  postgresql: "9.6"
notifications:
  slack:
    secure: O9in7h6grBN29Ec1pCZnxU9pR6x25135uuMLmrplF0LHDAIbB9xQfAFS3Ww0HfBEOE+bAdj5/mPGiM3gqKQUjjX8Bc1wFhy8gMB6zJ6xugdCrCfyjleKSqeaJYWNcmBAtLCuqUntc9L/xqusafwn9+lSZhDa8MFO2oVaZDtktR9QkpPIuLDXHtCnK0eVgKUrXQmsPrHexggimREi9gkCmT4y3Ec5N6f6EJO/GqwTnPc+uTpXiZXRR0LNjGx9qsUZUVN3y15lQfznw6qJ6BWdsv1aUTbvyXJkXYxztX98Sgy8jJllpktmpYb54tm4C8mziab2YjPHlRwDJeBaP73eDf/BhZP5PJqqLJsO9sWhL4S7CcJDxpkP5o+qf/+ddyfcoR8B1peBi636/nzNmLQDRfDLgx/4Anm6afBDBngrTOhj1hcw9E7hCPiSxlA0HaEjvkJFpxfIXt3gWabcRtSSp2yZxS/zXZ+/R3Wy3inv9CxY7hajDH0A3BdMGi/sjh/RD0Cw9/pXh4CvKW+R1uO09e5gCyDXXI6nSjOnhpjfStBHZJqhdyt8YTGHPdihKJndH3onriH7QZsX8WB4vfMM4X78tjfVwHkf6njhQ2+xjSSGvZFFfApXU6AItMwsK0AJnP46rgSYSUE7I8Qe5WvyefJQS+jRrpEcNghNXMxFR3E=
