---
development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 10
  username: postgres
  password:
  host: localhost
  # host: db

test:
  <<: *default
  database: app_test
