process_ledgers:
  cron: "*/10 * * * * *"
  class: "ForwardSyncLedgersJob"
  active_job: true

process_pending_reports:
  cron: "*/10 * * * * *"
  class: "ProcessPendingReportsJob"
  active_job: true
