#!/bin/bash

# This makes sure the script fails on the first failing command
set -e

. ./scripts/build-base

docker build --rm=false \
  --file=ops/prod/Dockerfile \
  --tag=$REPO_NAME:prod-latest \
  --tag=$REPO_NAME:prod-$GIT_REF \
  .
docker push $REPO_NAME:prod-latest
docker push $REPO_NAME:prod-$GIT_REF
